# Generated by Django 5.2.10 on 2026-05-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
    ]
